name: flutter_application_1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.0
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  dynamic_fonts: ^2.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  



  
  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: 'assets/images/logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 
  



flutter:
  uses-material-design: true
  assets:
    - assets/images/01.jpg
    - assets/images/02.jpg
    - assets/images/03.jpg
    - assets/images/04.jpg
    - assets/images/05.jpg
    - assets/images/06.jpg
    - assets/images/07.jpg
    - assets/images/08.jpg
    - assets/images/09.jpg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/15.jpg
    - assets/images/16.jpg
    - assets/images/17.jpg
    - assets/images/18.jpg
    - assets/images/20.jpg
    - assets/images/21.jpg
    - assets/images/22.jpg
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/car1.jpg
    - assets/images/car2.jpg
    - assets/images/car3.jpg
    


